methods page translation created
mprcodes/swift-book-es pull request #21
Opened 2023-01-11 08:25 UTC by oscar-moreno

2023-01-11 08:28 UTC, oscar-moreno commented
No estoy seguro al 100% que la traducción correcta para 'type-level methods' sea 'métodos de tipo nivel'.

2023-01-12 06:16 UTC, oscar-moreno commented
Listo para revisar

2023-01-23 12:03 UTC, mprcodes requested changes
Gracias por la traducción de este artículo, @oscar-moreno. Te he dejado algunas observaciones y cambios por hacer. Puede que te parezcan mucho, pero soy un poco estricto con la claridad y consistencia del contenido. En todo caso, agradezco mucho tu colaboración y espero que puedas seguir ayudando al proyecto.

Hazme saber cuando apliques los cambios para hacer merge del PR.

Una vez más, muchas gracias. Feliz día.

2023-01-23 17:44 UTC, oscar-moreno commented
> Gracias por la traducción de este artículo, @oscar-moreno. Te he dejado algunas observaciones y cambios por hacer. Puede que te parezcan mucho, pero soy un poco estricto con la claridad y consistencia del contenido. En todo caso, agradezco mucho tu colaboración y espero que puedas seguir ayudando al proyecto.
> 
> Hazme saber cuando apliques los cambios para hacer merge del PR.
> 
> Una vez más, muchas gracias. Feliz día.

Hola @mprcodes, claro, sin problema, lo entiendo perfectamente 🙂

Te aviso en cuanto aplique los cambios. Espero hacerlo esta semana y seguir contribuyendo. 

Un saludo.

2023-01-29 10:23 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
Cierto, olvidé traducir el "Here's an example...". 

Si no me equivoco, en Sudamérica se usa más a menudo "acá", mientras que en España solemos utilizar "aquí". ¿Como ves lo siguiente para hacerlo más neutro? "A continuación tenemos un ejemplo que define una clase sencilla..."

Quedo a la espera de confirmación

2023-01-29 10:30 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La clase `Jugador` crea una nueva instancia de `RegistroDeNivel` para registrar el progreso de los jugadores. También facilita un método llamado `completar(nivel:)`, que es llamado cuando un jugador
- Corrijo con lo indicado, pero indico "..., el cual es invocado cada vez que un jugador...".
- Añado tilde en línea (no la había incluido en la traducción que hice)
¿No deberíamos incluir los paréntesis también? "... (El valor booleano ... en la línea anterior)" Quedo a la espera de confirmación

2023-01-29 10:31 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los _Métodos_ son funciones asociadas con un tipo particular. Las clases, estructuras y enumeraciones pueden definir métodos de instancias, los cuales encapsulan tareas y funcionalidades específicas
Preparado para commit

2023-01-29 10:31 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +El hecho de que las estructuras y enumeraciones puedan definir métodos en Swift es la mayor diferencia desde C y Objective-C. En Objective-C, las clases son los únicos tipos que pueden definir método
Preparado para commit

2023-01-29 10:32 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los _Métodos de instancia_ son funciones que pertenecen a las instancias de una clase, estructura o enumeración en particular. Soportan la funcionalidad de dichas instancias, tanto proporcionando for
Preparado para commit

2023-01-29 10:32 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Un método de instancia se escribe dentro de las llaves de apertura y cierre del tipo que lo contiene. Un método de instancia tiene acceso implícito a todos los métodos de instancias y propiedades de
Preparado para commit

2023-01-29 10:32 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La estructura `RegistroDeNivel` se usa con la clase `Jugador`, mostrada más abajo, para registrar y actualizar el progreso de un jugador individual:
Preparado para commit

2023-01-29 10:32 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +    var regitro = RegistroDeNivel()
Preparado para commit

2023-01-29 10:32 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Si creas un segundo jugador, que intentes mover a un nivel que no ha sido aún desbloqueado por ningún jugador en el juego, el intento para establecer el nivel actual del jugador fallará:
Preparado para commit

2023-01-29 10:36 UTC, oscar-moreno commented
Hola @mprcodes, gracias por la revisión.

He aplicado los cambios indicados, excepto en dos 2 detalles, en los que quedo a la espera de confirmación. En cuanto puedas revisarlos e indicarme subo los cambios.

Que tengas un buen día 🙂

2023-01-29 14:14 UTC, mprcodes commented on pages/guia-del-lenguaje/metodos.mdx
Estoy de acuerdo con tu propuesta, Óscar.

2023-01-29 15:55 UTC, mprcodes commented on pages/guia-del-lenguaje/metodos.mdx
> +La clase `Jugador` crea una nueva instancia de `RegistroDeNivel` para registrar el progreso de los jugadores. También facilita un método llamado `completar(nivel:)`, que es llamado cuando un jugador
Supongo que ese enunciado entre paréntesis fue introducido como una acotación del autor (lo cual es común en guiones de obras teatrales y similares, más no en documentos técnicos). En todo caso, si se dejaran los paréntesis (y el enunciado que contienen), estos irían inmediatamente después del enunciado anterior y no separados mediante punto, es decir:
> ...al siguiente nivel (el valor booleano devuelto por `avanzar(a:)` es ignorado porque —mediante el llamado a `RegistroDeNivel.desbloquear()_:` en la linea anterior— se sabe que el nivel ya ha sido desbloqueado).

2023-01-29 16:00 UTC, mprcodes commented
Hola, @oscar-moreno. Veo que a algunas de las observaciones que te dejé les comentaste indicando que estaban listos para commit y a otras no, por lo que no me queda claro si algunas las pasaste por alto o simplemente sí las revisaste pero no comentaste en todas.

En caso de que hayas pasado las otras por alto, puede haber sido porque GitHub las muestra ocultas (dado el número de comments), y tendrías que expandirlas.

<img width="1415" alt="Screenshot 2023-01-29 at 10 56 28 AM" src="https://user-images.githubusercontent.com/49292621/215338692-fb4bec82-3eae-4eb7-81b9-e4de0107fb1b.png">

En caso contrario, haz el commit para darle una última revisión.

Feliz día.

2023-01-30 11:02 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
Preparado para commit

2023-01-30 11:05 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
>  </CodeSnippet>
Preparado para commit

2023-01-30 11:05 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +- `incrementar(en: Int)` incrementa el contador en una cantidad entera especificada.
Preparado para commit

2023-01-30 11:05 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los métodos de instancia se llaman con la misma sintaxis de puntuación que las propiedades:
Preparado para commit

2023-01-30 11:11 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
Pendiente de confirmación de comentario anterior para proceder con segunda indicación

2023-01-30 11:13 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Todas las instancias de tipo tienen de forma implícita una propiedad llamada `self`, que es exactamente equivalente a la propia instancia. Utiliza la propiedad `self` para referirte a la instancia ac
Preparado para commit

2023-01-30 11:14 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +El método `incrementar()` del ejemplo de más arriba, se podría haber escrito así:
Preparado para commit

2023-01-30 11:14 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +    self.contador += 1
Preparado para commit

2023-01-30 11:15 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +En la práctica, no necesitas escribir `self` a menudo en tu código. Si no escribes explícitamente `self`, Swift asume que te estás refiriendo a una propiedad o método de la actual instancia siempre y
Preparado para commit

2023-01-30 11:16 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La principal excepción a esta regla ocurre cuando un nombre de parámetro para un método de instancia tiene el mismo nombre que la propiedad de esa instancia. En esta situación, el nombre del parámetr
Preparado para commit

2023-01-30 11:16 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Aquí, `self`diferencia entre un parámetro de método llamado `x` y una propiedad de instancia también llamada `x`:
Preparado para commit

2023-01-30 11:17 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +## Modificando Tipos por valor desde dentro de Métodos de instancia
Preparado para commit

2023-01-30 11:19 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Las estructuras y enumeraciones son _tipos por valor_. Por defecto, las propiedades de un tipo por valor no pueden ser modificadas desde dentro de sus métodos de instancia.
Entiendo que el segundo cambio debe ser reemplazar: `...propiedades de un tipo por valor no pueden...` por `...propiedades de un tipo de valor no pueden...`

Preparado para commit. Avisar si no es correcto

2023-01-30 11:20 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Sin embargo, si necesitas modificar las propiedades de tu estructura o enumeración dentro de un método particular, puedes optar por _mutar_ el comportamiento de ese método. El método puede entonces m
Preparado para commit

2023-01-30 11:20 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Puedes optar por este comportamiento situando la palabra clave `mutating` antes de la palabra clave `func` para ese método:
Preparado para commit

2023-01-30 11:22 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +    mutating func moverA(x deltaX: Double, y deltaY: Double) {
Estoy de acuerdo 🙂

Preparado para commit

2023-01-30 11:26 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La estructura anterior `Punto` define un método mutable `moverA(x:y:)`, que mueve una instancia de `Punto` en una cierta cantidad. En lugar de devolver un nuevo punto, este método modifica el punto e
En relación al comentario anterior del uso de "en" o "por" en cantidades, yo escribiría lo solicitado excepto: `... por una determinada cantidad...` en la que indicaría `... en una determinada cantidad...`

Quedo a la espera de confirmación

2023-01-30 11:45 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Fíjate que no puedes llamar un método mutable en un tipo estructura constante, porque sus propiedades no pueden ser cambiadas, aunque sean propiedades variables, como se describe en [Propiedades alma
Preparado para commit

2023-01-30 11:46 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +algunPunto.moverA(x: 2.0, y: 3.0)\n
Preparado para commit

2023-01-30 11:46 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +puntoFijo.moverA(x: 2.0, y: 3.0)
Preparado para commit

2023-01-30 11:47 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +### Asignando a `self` dentro de un método mutable
Preparado para commit

2023-01-30 11:48 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los métodos mutables pueden asignar toda una nueva instancia a la propiedad implícita `self`. El ejemplo `Punto` mostrado más arriba, podría haber sido en su lugar escrito de la siguiente forma:
Preparado para commit

2023-01-30 11:48 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +    mutating func moverA(x deltaX: Double, y deltaY: Double) {
Preparado para commit

2023-01-30 11:52 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Esta versión del método mutable `moverA(x:y:)` crea una nueva estructura cuyos valores `x` e `y` son establecidos a la localización de destino. El resultado final de llamar a esta versión alternativa
Entiendo que la coordenada `y` es `i(griega)` no es `ye`, por lo aplico lo indicado pero escribiendo: "...cuyos valores `x` e `y`...". Según https://www.rae.es/duda-linguistica/para-las-coordenadas-es-x-y-y-o-x-e-y

Preparado para commit. De no ser así, avisar para corregirlo.

2023-01-30 13:54 UTC, mprcodes commented on pages/guia-del-lenguaje/metodos.mdx
>  </CodeSnippet>
Tienes razón, mantedremos el uso de «en».

2023-01-30 14:07 UTC, mprcodes commented on pages/guia-del-lenguaje/metodos.mdx
> +Esta versión del método mutable `moverA(x:y:)` crea una nueva estructura cuyos valores `x` e `y` son establecidos a la localización de destino. El resultado final de llamar a esta versión alternativa
Bueno, en América Latina solemos nombrar a la variable como «ye» (en lugar de «i griega»), por lo que, en tal caso, usaría _«valores de x e y»_. ¿Es común en España llamarle «i griega»? En matemáticas (u otras ciencias básicas), por ejemplo?

2023-02-04 14:13 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
>  </CodeSnippet>
preparado para commit

2023-02-04 14:14 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +- `incrementar(en: Int)` incrementa el contador en una cantidad entera especificada.
corrijo punto 1, punto 2 mantengo "en" según lo confirmado previamente. Preparado para commit.

2023-02-04 14:15 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La clase `Contador` también declara una propiedad variable, `contador`, para mantener el registro del valor actual del contador.
Preparado para commit

2023-02-04 14:16 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los parámetros de función pueden tener tanto un nombre (para usar en el cuerpo de la función) como una etiqueta de argumento (para usar cuando se llama a la función), como se describe en [Etiquetas d
Preparado para commit

2023-02-04 14:17 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +### La Propiedad `self`
Preparado para commit

2023-02-04 14:20 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La estructura anterior `Punto` define un método mutable `moverA(x:y:)`, que mueve una instancia de `Punto` en una cierta cantidad. En lugar de devolver un nuevo punto, este método modifica el punto e
Preparado para commit

2023-02-04 14:31 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Esta versión del método mutable `moverA(x:y:)` crea una nueva estructura cuyos valores `x` e `y` son establecidos a la localización de destino. El resultado final de llamar a esta versión alternativa
Gracias por la info Mauricio, no lo sabía. Sí en España se nombra "i griega", pero únicamente cuando se nombra la letra y está sola, por ejemplo: "La penúltima letra del abecedario es la i griega". En expresiones matemáticas, simplemente se dice "i": "Los valores de 'equis' e 'i' ". Entiendo en todo caso que es correcto tanto "valores de x y y", como "valores de x e y". Procedo como indiques (Por si se da el caso en otra página, para que sea acorde con el resto). Quedo a la espera de confirmación.

2023-02-04 14:32 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los métodos mutables para enumeraciones pueden establecer el parámetro implícito `self` para ser un caso diferente desde la misma enumeración:
Preparado para commit

2023-02-04 14:34 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +// luzDelHorno ahora es igual a .apagada`}
Preparado para commit

2023-02-04 14:36 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Este ejemplo define una enumeración para un swift de tres estados. El switch pasa por los tres diferentes estados de encendido (`apagada`, `baja`, y `alta`) siempre que el método `next()` es llamado.
Preparado para commit

2023-02-04 14:39 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los métodos de instancia, como se describe más arriba, son métodos que llamas en una instancia de un tipo particular. También puedes definir métodos que son llamados en el propio tipo. Estos tipos de
Preparado para commit

2023-02-04 14:39 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +  del tipo que lo soporta.
Preparado para commit

2023-02-04 14:40 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Los métodos de tipo se llaman con la sintaxis de puntación, como los métodos de instancia. Sin embargo, llama a los métodos de tipos en el tipo, no en una instancia de ese tipo. Aquí puedes ver como
Preparado para commit

2023-02-04 14:41 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Dentro del cuerpo de un método de tipo, la propiedad implícita `self` se refiere al tipo mismo, en lugar de a una instancia de ese tipo. Esto significa que puedes usar `self` para diferenciar entre p
Preparado para commit

2023-02-04 14:42 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Todos los niveles del juego (excepto el nivel uno) están bloqueados cuando se juega por primera vez. Cada vez que un jugador finaliza un nivel, ese nivel se desbloquea para todos los jugadores en el
Preparado para commit

2023-02-04 14:44 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +    static var nivelMasAltoDesbloqueado = 1
Preparado para commit

2023-02-04 14:44 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +        if nivel > nivelMasAltoDesbloqueado { nivelMasAltoDesbloqueado = nivel }
Preparado para commit

2023-02-04 14:44 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +        return nivel <= nivelMasAltoDesbloqueado
Preparado para commit

2023-02-04 14:45 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +print("ahora el nivel más alto desbloqueado es \\(RegistroDeNivel.nivelMasAltoDesbloqueado)")
Preparado para commit

2023-02-04 14:46 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La estructura `RegistroDeNivel` mantiene el registro del nivel más alto que un jugador ha desbloqueado. Este valor se almacena en una propiedad de tipo llamada `nivelMasAltoDesbloqueado`.
Preparado para commit

2023-02-04 14:49 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +`RegistroDeNivel` también define dos funciones de tipo para trabajar con la propiedad `nivelMasAltoDesbloqueado`. La primera es una función de tipo llamada `desbloquear(_:)`. que actualiza el valor d
Preparado para commit

2023-02-04 14:50 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Además de su propiedad de tipo y sus métodos de tipo, `RegistroDeNivel` registra el progreso individual de los jugadores a través del juego. Usa una propiedad de instancia llamada `nivelActual` para
Preparado para commit

2023-02-04 14:53 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +Para ayudar a gestionar la propiedad `nivelActual`, `RegistroDeNivel` define un método de instancia llamado `avanzar(a:)`. Antes de actualizar `nivelActual`, este método comprueba si el nuevo nivel s
Procedo al cambio, excepto en error ortográfico: En lugar de `...está función va marcada...` escribo `...esta función va marcada...` 
Preparado para commit

2023-02-04 14:58 UTC, oscar-moreno commented on pages/guia-del-lenguaje/metodos.mdx
> +La clase `Jugador` crea una nueva instancia de `RegistroDeNivel` para registrar el progreso de los jugadores. También facilita un método llamado `completar(nivel:)`, que es llamado cuando un jugador
Cierto, estoy de acuerdo. Corrijo según último comentario.

Preparado para commit

2023-02-04 15:07 UTC, oscar-moreno commented
Hola @mprcodes. He aplicado la mayoría de los cambios indicados. Únicamente faltaría el que queda por resolver. Quedo a la espera de confirmación para proceder y hacer el commit de ese fragmento. 

Un saludo y feliz día 🙂

2023-02-15 20:45 UTC, merged